POST /v2/order HTTP/1.1
Host: api.test.zoopit.no
api-key: <<<YOUR_API_KEY>>>
Content-Type: application/json
Cache-Control: no-cache


{
	"quote_id" : <<<A_VALID_QUOTE_ID>>>,
	"send" : true,
	"remote_id" : "Referanse ID",
	 "pickup" : {
			"customer" : {
				"firstname" : "Test",
				"lastname"  : "Test"
			},
			"address" : {
				"country" : "Norway",
				"city"    : "Oslo",
				"street"  : "Akersgata 55",
				"zip"     : "0180"
			},
			"contact" : {
				"email" : "trygve@zoopit.no",
				"phone" : "98816942"
			},
			"comments" : [""]
	  },
		"delivery": {
			"customer" : {
				"firstname" : "Test",
				"lastname"  : "Test"
			},
		"address" : {
			"country" : "Norway",
				"city"    : "Oslo",
				"street"  : "Akersgata 55",
				"zip"     : "0180"
			},
			"contact" : {
				"email" : "trygve@zoopit.no",
				"phone" : "98816942"
			},
			"comments" : [""]
		}
	}